[HanPeaceSansJP-Regular]
	f=3,1,0x411,\6E90\30CE\89D2\30B4\30B7\30C3\30AF JP
	s=3,1,0x411,Regular
	f=Han Peace Sans JP
	s=Regular

[HanPeaceSansJP-Bold]
	f=3,1,0x411,\6E90\30CE\89D2\30B4\30B7\30C3\30AF JP
	s=3,1,0x411,Bold
	f=Han Peace Sans JP
	s=Bold

[HanPeaceSansKR-Regular]
	f=3,1,0x412,\BCF8\ACE0\B515 KR
	s=3,1,0x412,Regular
	f=Han Peace Sans KR
	s=Regular

[HanPeaceSansKR-Bold]
	f=3,1,0x412,\BCF8\ACE0\B515 KR
	s=3,1,0x412,Bold
	f=Han Peace Sans KR
	s=Bold

[HanPeaceSansCN-Regular]
	f=3,1,0x804,\601D\6E90\9ED1\4F53 CN
	s=3,1,0x804,Regular
	f=Han Peace Sans CN
	s=Regular

[HanPeaceSansCN-Bold]
	f=3,1,0x804,\601D\6E90\9ED1\4F53 CN
	s=3,1,0x804,Bold
	f=Han Peace Sans CN
	s=Bold

[HanPeaceSansTW-Regular]
	f=3,1,0x404,\601D\6E90\9ED1\9AD4 TW
	s=3,1,0x404,Regular
	f=Han Peace Sans TW
	s=Regular

[HanPeaceSansTW-Bold]
	f=3,1,0x404,\601D\6E90\9ED1\9AD4 TW
	s=3,1,0x404,Bold
	f=Han Peace Sans TW
	s=Bold
