[HanPeaceSans-Regular]
	f=3,1,0x411,\6E90\30CE\89D2\30B4\30B7\30C3\30AF
	s=3,1,0x411,Regular
	f=Han Peace Sans
	s=Regular

[HanPeaceSans-Bold]
	f=3,1,0x411,\6E90\30CE\89D2\30B4\30B7\30C3\30AF
	s=3,1,0x411,Bold
	f=Han Peace Sans
	s=Bold

[HanPeaceSansK-Regular]
	f=3,1,0x412,\BCF8\ACE0\B515
	s=3,1,0x412,Regular
	f=Han Peace Sans K
	s=Regular

[HanPeaceSansK-Bold]
	f=3,1,0x412,\BCF8\ACE0\B515
	s=3,1,0x412,Bold
	f=Han Peace Sans K
	s=Bold

[HanPeaceSansSC-Regular]
	f=3,1,0x804,\601D\6E90\9ED1\4F53
	s=3,1,0x804,Regular
	f=Han Peace Sans SC
	s=Regular

[HanPeaceSansSC-Bold]
	f=3,1,0x804,\601D\6E90\9ED1\4F53
	s=3,1,0x804,Bold
	f=Han Peace Sans SC
	s=Bold

[HanPeaceSansTC-Regular]
	f=3,1,0x404,\601D\6E90\9ED1\9AD4
	s=3,1,0x404,Regular
	f=Han Peace Sans TC
	s=Regular

[HanPeaceSansTC-Bold]
	f=3,1,0x404,\601D\6E90\9ED1\9AD4
	s=3,1,0x404,Bold
	f=Han Peace Sans TC
	s=Bold
