[HanPeaceSansHW-Regular]
	f=3,1,0x411,\6E90\30CE\89D2\30B4\30B7\30C3\30AF HW
	s=3,1,0x411,Regular
	f=Han Peace Sans HW
	s=Regular

[HanPeaceSansHW-Bold]
	f=3,1,0x411,\6E90\30CE\89D2\30B4\30B7\30C3\30AF HW
	s=3,1,0x411,Bold
	f=Han Peace Sans HW
	s=Bold

[HanPeaceSansHWK-Regular]
	f=3,1,0x412,\BCF8\ACE0\B515 HW
	s=3,1,0x412,Regular
	f=Han Peace Sans HW K
	s=Regular

[HanPeaceSansHWK-Bold]
	f=3,1,0x412,\BCF8\ACE0\B515 HW
	s=3,1,0x412,Bold
	f=Han Peace Sans HW K
	s=Bold

[HanPeaceSansHWSC-Regular]
	f=3,1,0x804,\601D\6E90\9ED1\4F53 HW
	s=3,1,0x804,Regular
	f=Han Peace Sans HW SC
	s=Regular

[HanPeaceSansHWSC-Bold]
	f=3,1,0x804,\601D\6E90\9ED1\4F53 HW
	s=3,1,0x804,Bold
	f=Han Peace Sans HW SC
	s=Bold

[HanPeaceSansHWTC-Regular]
	f=3,1,0x404,\601D\6E90\9ED1\9AD4 HW
	s=3,1,0x404,Regular
	f=Han Peace Sans HW TC
	s=Regular

[HanPeaceSansHWTC-Bold]
	f=3,1,0x404,\601D\6E90\9ED1\9AD4 HW
	s=3,1,0x404,Bold
	f=Han Peace Sans HW TC
	s=Bold
